//! Cross-verification tests against real Reticulum Python test vectors.
//!
//! These vectors were generated by running the Reticulum Python reference
//! implementation and exporting key material, signatures, and ciphertexts.
//! Passing these tests proves byte-level interoperability with Reticulum.

use harmony_crypto::hash;
use harmony_identity::{Identity, PrivateIdentity};

/// Test vectors generated from Reticulum Python (RNS.Identity).
mod vectors {
    pub const X25519_PRIVATE: &str =
        "20373f976f707a256b450d7bd63b7230978fa623395a9bc91edd890a5a38654b";
    pub const ED25519_PRIVATE: &str =
        "f25ade2a1327293ccb885f4bfdaabdd4a64708ba40c7a4410bdcf1ddaccd7dfa";
    pub const X25519_PUBLIC: &str =
        "e080f2b82f9a08581008c8391e0a5e1e29da4b49d5364e7dbb1a20caf4a1ea57";
    pub const ED25519_PUBLIC: &str =
        "685cf6f3f7887d5b10b6efcbdcecaf5efe908e7b002c57c53547d6df1f1a962c";
    pub const ADDRESS_HASH: &str = "af0de81878d6685b62d3459968c2d9f2";
    pub const COMBINED_PUBLIC: &str =
        "e080f2b82f9a08581008c8391e0a5e1e29da4b49d5364e7dbb1a20caf4a1ea57\
         685cf6f3f7887d5b10b6efcbdcecaf5efe908e7b002c57c53547d6df1f1a962c";

    pub const SIGN_MESSAGE: &str = "6861726d6f6e7920696e7465726f702074657374206d657373616765";
    pub const SIGNATURE: &str = "f4074a5045d06b779004c08f4dfd0daf6923c8746e2493ddc70bf882e98abcea\
         3a3fe75da5e4990c53dd0c293f501447312dba6f900710d9435e34a66294aa09";

    pub const ENCRYPT_PLAINTEXT: &str = "68656c6c6f2066726f6d207265746963756c756d20707974686f6e";
    pub const ENCRYPT_CIPHERTEXT: &str =
        "2fbe26fc3ce9f604e09d26881e1a805c21ea379cfd40b8741254bc92e270a20a\
         ed8fb66b9d56b90d2483989aba56b5b27007c59738505076bf4169abe0492260\
         1d1f98d358d3e4d70707320c594ae1d0e58b297164d662ca4d7c0fa92cfe50ad\
         9ddf653538bd70f1d0d8a8aabff15f2e";

    pub const ID2_X25519_PRIVATE: &str =
        "400b83cab205e3383838868344ed4e52c94da309d1a6d6098289768104877353";
    pub const ID2_ED25519_PRIVATE: &str =
        "e6bdab8f004a72904d8c62c692a5e8cf1db023f7d6f973072fcf56265bac7175";
    pub const ID2_ADDRESS_HASH: &str = "d9b3e6139565245d1a434975430956d2";

    pub const CROSS_ENCRYPT_PLAINTEXT: &str =
        "63726f73732d6964656e7469747920656e6372797074696f6e2074657374";
    pub const CROSS_ENCRYPT_CIPHERTEXT: &str =
        "6bee97688961561418bb283b163d9037307c42579f92728f45e5fddc44c78114\
         6bfa9f0820e7e28f9ef3754cd19a7d9b66feb5c632cb6bf64123a1272053c2dc\
         e1eef7ff4a61e18b0b2d7eadf069410bf35bb286afa2eb55903bdf458b250df7\
         9f6060a48ce828f850e46d95f5aca45a";
}

fn decode_hex(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap()
}

// ── Address Derivation Interop ──────────────────────────────────────────

#[test]
fn reticulum_address_hash_matches() {
    let combined = decode_hex(vectors::COMBINED_PUBLIC);
    let expected_hash = decode_hex(vectors::ADDRESS_HASH);
    let computed = hash::truncated_hash(&combined);
    assert_eq!(
        computed.as_slice(),
        expected_hash.as_slice(),
        "Address hash mismatch with Reticulum Python"
    );
}

#[test]
fn reticulum_identity_from_public_bytes() {
    let combined = decode_hex(vectors::COMBINED_PUBLIC);
    let identity = Identity::from_public_bytes(&combined).unwrap();
    let expected_hash = decode_hex(vectors::ADDRESS_HASH);
    assert_eq!(identity.address_hash.as_slice(), expected_hash.as_slice());
}

#[test]
fn reticulum_identity_from_private_bytes() {
    let mut priv_bytes = [0u8; 64];
    priv_bytes[..32].copy_from_slice(&decode_hex(vectors::X25519_PRIVATE));
    priv_bytes[32..].copy_from_slice(&decode_hex(vectors::ED25519_PRIVATE));
    let identity = PrivateIdentity::from_private_bytes(&priv_bytes).unwrap();

    let pub_bytes = identity.public_identity().to_public_bytes();
    assert_eq!(
        &pub_bytes[..32],
        decode_hex(vectors::X25519_PUBLIC).as_slice()
    );
    assert_eq!(
        &pub_bytes[32..],
        decode_hex(vectors::ED25519_PUBLIC).as_slice()
    );
    assert_eq!(
        identity.public_identity().address_hash.as_slice(),
        decode_hex(vectors::ADDRESS_HASH).as_slice()
    );
}

// ── Signature Verification Interop ──────────────────────────────────────

#[test]
fn verify_reticulum_python_signature() {
    let combined_pub = decode_hex(vectors::COMBINED_PUBLIC);
    let identity = Identity::from_public_bytes(&combined_pub).unwrap();

    let message = decode_hex(vectors::SIGN_MESSAGE);
    let signature: [u8; 64] = decode_hex(vectors::SIGNATURE).try_into().unwrap();

    identity
        .verify(&message, &signature)
        .expect("Failed to verify Reticulum Python signature");
}

#[test]
fn harmony_signature_matches_reticulum() {
    // Ed25519 is deterministic (RFC 8032): same key + message = same signature
    let mut priv_bytes = [0u8; 64];
    priv_bytes[..32].copy_from_slice(&decode_hex(vectors::X25519_PRIVATE));
    priv_bytes[32..].copy_from_slice(&decode_hex(vectors::ED25519_PRIVATE));
    let identity = PrivateIdentity::from_private_bytes(&priv_bytes).unwrap();

    let message = decode_hex(vectors::SIGN_MESSAGE);
    let harmony_sig = identity.sign(&message);
    let reticulum_sig = decode_hex(vectors::SIGNATURE);

    assert_eq!(
        harmony_sig.as_slice(),
        reticulum_sig.as_slice(),
        "Harmony and Reticulum produce different Ed25519 signatures"
    );
}

// ── Decryption Interop ──────────────────────────────────────────────────

#[test]
fn decrypt_reticulum_python_ciphertext() {
    let mut priv_bytes = [0u8; 64];
    priv_bytes[..32].copy_from_slice(&decode_hex(vectors::X25519_PRIVATE));
    priv_bytes[32..].copy_from_slice(&decode_hex(vectors::ED25519_PRIVATE));
    let identity = PrivateIdentity::from_private_bytes(&priv_bytes).unwrap();

    let ciphertext = decode_hex(vectors::ENCRYPT_CIPHERTEXT);
    let plaintext = identity
        .decrypt(&ciphertext)
        .expect("Failed to decrypt Reticulum Python ciphertext");

    assert_eq!(plaintext, decode_hex(vectors::ENCRYPT_PLAINTEXT));
}

#[test]
fn decrypt_reticulum_cross_identity_ciphertext() {
    let mut priv_bytes = [0u8; 64];
    priv_bytes[..32].copy_from_slice(&decode_hex(vectors::ID2_X25519_PRIVATE));
    priv_bytes[32..].copy_from_slice(&decode_hex(vectors::ID2_ED25519_PRIVATE));
    let identity2 = PrivateIdentity::from_private_bytes(&priv_bytes).unwrap();

    assert_eq!(
        identity2.public_identity().address_hash.as_slice(),
        decode_hex(vectors::ID2_ADDRESS_HASH).as_slice()
    );

    let ciphertext = decode_hex(vectors::CROSS_ENCRYPT_CIPHERTEXT);
    let plaintext = identity2
        .decrypt(&ciphertext)
        .expect("Failed to decrypt identity2 ciphertext");

    assert_eq!(plaintext, decode_hex(vectors::CROSS_ENCRYPT_PLAINTEXT));
}

// ── Bidirectional: Harmony encrypts, Harmony decrypts with Reticulum keys ──

#[test]
fn harmony_encrypt_decrypt_with_reticulum_keys() {
    use rand::rngs::OsRng;

    let mut priv_bytes = [0u8; 64];
    priv_bytes[..32].copy_from_slice(&decode_hex(vectors::X25519_PRIVATE));
    priv_bytes[32..].copy_from_slice(&decode_hex(vectors::ED25519_PRIVATE));
    let priv_identity = PrivateIdentity::from_private_bytes(&priv_bytes).unwrap();

    let plaintext = b"harmony encrypts, reticulum key decrypts";
    let ciphertext = priv_identity
        .public_identity()
        .encrypt(&mut OsRng, plaintext)
        .unwrap();

    // 32 ephemeral X25519 pub + at least 64-byte Fernet token (IV + 1 AES block + HMAC)
    assert!(ciphertext.len() >= 96);

    let decrypted = priv_identity.decrypt(&ciphertext).unwrap();
    assert_eq!(decrypted, plaintext);
}
