use crate::cid::MAX_PAYLOAD_SIZE;
use crate::error::ContentError;

/// Generate a 256-entry Gear hash lookup table at compile time using SplitMix64.
const fn generate_gear_table(seed: u64) -> [u64; 256] {
    let mut table = [0u64; 256];
    let mut state = seed;
    let mut i = 0;
    while i < 256 {
        // SplitMix64 step
        state = state.wrapping_add(0x9e3779b97f4a7c15);
        let mut z = state;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d049bb133111eb);
        z = z ^ (z >> 31);
        table[i] = z;
        i += 1;
    }
    table
}

/// Gear hash lookup table: 256 entries generated by SplitMix64 with seed 0.
///
/// Used by the FastCDC content-defined chunking algorithm. Each byte of input
/// is mapped through this table to produce a rolling hash with good statistical
/// properties.
const GEAR_TABLE: [u64; 256] = generate_gear_table(0);

/// Configuration for the FastCDC content-defined chunker.
///
/// Controls the minimum, average, and maximum chunk sizes produced by the
/// chunking algorithm. The average size must be a power of two (used as the
/// gear-hash mask), and all sizes must satisfy `min < avg < max <= MAX_PAYLOAD_SIZE`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ChunkerConfig {
    /// Minimum chunk size in bytes. The chunker will never split below this.
    pub min_chunk: usize,
    /// Target average chunk size in bytes. Must be a power of two.
    pub avg_chunk: usize,
    /// Maximum chunk size in bytes. The chunker will force a split at this point.
    pub max_chunk: usize,
}

impl ChunkerConfig {
    /// Default configuration: 256 KiB min, 512 KiB avg, ~1 MiB max.
    pub const DEFAULT: Self = Self {
        min_chunk: 256 * 1024,
        avg_chunk: 512 * 1024,
        max_chunk: MAX_PAYLOAD_SIZE,
    };

    /// Validate that this configuration is well-formed.
    ///
    /// Returns `Ok(())` if all invariants hold, or an `InvalidChunkerConfig`
    /// error describing the first violation found.
    pub fn validate(&self) -> Result<(), ContentError> {
        if self.min_chunk == 0 {
            return Err(ContentError::InvalidChunkerConfig {
                reason: "min_chunk must be greater than zero",
            });
        }
        if !self.avg_chunk.is_power_of_two() {
            return Err(ContentError::InvalidChunkerConfig {
                reason: "avg_chunk must be a power of two",
            });
        }
        if self.min_chunk >= self.avg_chunk {
            return Err(ContentError::InvalidChunkerConfig {
                reason: "min_chunk must be less than avg_chunk",
            });
        }
        if self.avg_chunk >= self.max_chunk {
            return Err(ContentError::InvalidChunkerConfig {
                reason: "avg_chunk must be less than max_chunk",
            });
        }
        if self.max_chunk > MAX_PAYLOAD_SIZE {
            return Err(ContentError::InvalidChunkerConfig {
                reason: "max_chunk must not exceed MAX_PAYLOAD_SIZE",
            });
        }
        Ok(())
    }
}

/// FastCDC content-defined chunker using the two-mask algorithm.
///
/// Scans a byte stream and identifies natural split points using a rolling
/// Gear hash. Two masks are used: a strict mask (`mask_s`) that produces fewer
/// boundaries in the `[min, norm_point)` region, and a loose mask (`mask_l`)
/// that produces more boundaries in the `[norm_point, max)` region. This
/// normalizes the chunk size distribution around the target average.
///
/// The chunker is stateful: call [`feed`](Chunker::feed) with successive data
/// slices, then [`finalize`](Chunker::finalize) to flush any remaining tail.
pub struct Chunker {
    min_chunk: usize,
    max_chunk: usize,
    /// Normalization point: `min_chunk + avg_chunk / 2`.
    norm_point: usize,
    /// Strict mask (fewer boundaries) for the `[min, norm)` region.
    mask_s: u64,
    /// Loose mask (more boundaries) for the `[norm, max)` region.
    mask_l: u64,
    /// Rolling Gear hash state.
    hash: u64,
    /// Bytes consumed since last cut point.
    pos: usize,
}

impl Chunker {
    /// Create a new chunker from the given configuration.
    ///
    /// The configuration is validated before use. Returns
    /// [`ContentError::InvalidChunkerConfig`] if any invariant is violated.
    pub fn new(config: ChunkerConfig) -> Result<Self, ContentError> {
        config.validate()?;

        let mask_l = config.avg_chunk as u64 - 1;
        let mask_s = (mask_l << 1) | 1;
        let norm_point = config.min_chunk + config.avg_chunk / 2;

        Ok(Self {
            min_chunk: config.min_chunk,
            max_chunk: config.max_chunk,
            norm_point,
            mask_s,
            mask_l,
            hash: 0,
            pos: 0,
        })
    }

    /// Feed a slice of data into the chunker and return cut-point offsets.
    ///
    /// Each returned offset is relative to the start of `data` and marks the
    /// position immediately after the last byte of a chunk (i.e., the first
    /// byte of the *next* chunk). The caller is responsible for slicing the
    /// original data accordingly.
    ///
    /// The chunker maintains internal state across calls, so a single logical
    /// stream can be fed in arbitrarily sized pieces.
    pub fn feed(&mut self, data: &[u8]) -> Vec<usize> {
        let mut cuts = Vec::new();

        for (i, &byte) in data.iter().enumerate() {
            self.hash = (self.hash << 1).wrapping_add(GEAR_TABLE[byte as usize]);
            self.pos += 1;

            // Force a cut at the hard maximum.
            if self.pos >= self.max_chunk {
                cuts.push(i + 1);
                self.hash = 0;
                self.pos = 0;
                continue;
            }

            // Below minimum — skip boundary check.
            if self.pos < self.min_chunk {
                continue;
            }

            // Choose mask based on normalization point.
            let mask = if self.pos < self.norm_point {
                self.mask_s
            } else {
                self.mask_l
            };

            if self.hash & mask == 0 {
                cuts.push(i + 1);
                self.hash = 0;
                self.pos = 0;
            }
        }

        cuts
    }

    /// Finalize the chunker, returning the remaining tail length if any.
    ///
    /// After calling this the chunker is reset and ready for reuse.
    pub fn finalize(&mut self) -> Option<usize> {
        let remaining = self.pos;
        self.hash = 0;
        self.pos = 0;
        if remaining > 0 {
            Some(remaining)
        } else {
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gear_table_is_deterministic() {
        let regenerated = generate_gear_table(0);
        assert_eq!(GEAR_TABLE, regenerated);
    }

    #[test]
    fn gear_table_has_no_obvious_patterns() {
        // No adjacent duplicates
        for i in 1..256 {
            assert_ne!(
                GEAR_TABLE[i - 1],
                GEAR_TABLE[i],
                "adjacent entries {} and {} are duplicates",
                i - 1,
                i
            );
        }
        // No zeros
        for (i, &entry) in GEAR_TABLE.iter().enumerate() {
            assert_ne!(entry, 0, "entry {} is zero", i);
        }
    }

    #[test]
    fn gear_table_first_entry_is_stable() {
        // Pin the first entry to detect seed or algorithm changes.
        assert_eq!(
            GEAR_TABLE[0], 0xe220a8397b1dcdaf,
            "first entry changed — seed or SplitMix64 algorithm was modified"
        );
    }

    // -----------------------------------------------------------------------
    // ChunkerConfig validation
    // -----------------------------------------------------------------------

    #[test]
    fn config_default_is_valid() {
        ChunkerConfig::DEFAULT.validate().unwrap();
    }

    #[test]
    fn config_rejects_zero_min() {
        let cfg = ChunkerConfig {
            min_chunk: 0,
            avg_chunk: 128,
            max_chunk: 256,
        };
        let err = cfg.validate().unwrap_err();
        assert!(err
            .to_string()
            .contains("min_chunk must be greater than zero"));
    }

    #[test]
    fn config_rejects_non_power_of_two_avg() {
        let cfg = ChunkerConfig {
            min_chunk: 64,
            avg_chunk: 100,
            max_chunk: 256,
        };
        let err = cfg.validate().unwrap_err();
        assert!(err.to_string().contains("avg_chunk must be a power of two"));
    }

    #[test]
    fn config_rejects_min_ge_avg() {
        let cfg = ChunkerConfig {
            min_chunk: 128,
            avg_chunk: 128,
            max_chunk: 256,
        };
        let err = cfg.validate().unwrap_err();
        assert!(err
            .to_string()
            .contains("min_chunk must be less than avg_chunk"));
    }

    #[test]
    fn config_rejects_avg_ge_max() {
        let cfg = ChunkerConfig {
            min_chunk: 64,
            avg_chunk: 256,
            max_chunk: 256,
        };
        let err = cfg.validate().unwrap_err();
        assert!(err
            .to_string()
            .contains("avg_chunk must be less than max_chunk"));
    }

    #[test]
    fn config_rejects_max_exceeding_payload() {
        let cfg = ChunkerConfig {
            min_chunk: 64,
            avg_chunk: 128,
            max_chunk: MAX_PAYLOAD_SIZE + 1,
        };
        let err = cfg.validate().unwrap_err();
        assert!(err
            .to_string()
            .contains("max_chunk must not exceed MAX_PAYLOAD_SIZE"));
    }

    #[test]
    fn config_small_valid() {
        let cfg = ChunkerConfig {
            min_chunk: 64,
            avg_chunk: 128,
            max_chunk: 256,
        };
        cfg.validate().unwrap();
    }

    // -----------------------------------------------------------------------
    // Chunker
    // -----------------------------------------------------------------------

    /// Helper: small config suitable for unit tests (min=64, avg=128, max=256).
    fn small_config() -> ChunkerConfig {
        ChunkerConfig {
            min_chunk: 64,
            avg_chunk: 128,
            max_chunk: 256,
        }
    }

    #[test]
    fn chunker_deterministic() {
        let data: Vec<u8> = (0u8..=255).cycle().take(2048).collect();

        let cuts1 = {
            let mut c = Chunker::new(small_config()).unwrap();
            let mut cuts = c.feed(&data);
            if let Some(tail) = c.finalize() {
                let last = cuts.last().copied().unwrap_or(0);
                cuts.push(last + tail);
            }
            cuts
        };

        let cuts2 = {
            let mut c = Chunker::new(small_config()).unwrap();
            let mut cuts = c.feed(&data);
            if let Some(tail) = c.finalize() {
                let last = cuts.last().copied().unwrap_or(0);
                cuts.push(last + tail);
            }
            cuts
        };

        assert_eq!(cuts1, cuts2, "same data must produce identical cut points");
        assert!(!cuts1.is_empty(), "expected at least one cut point");
    }

    #[test]
    fn chunker_respects_min_max() {
        let data: Vec<u8> = (0u8..=255).cycle().take(4096).collect();
        let cfg = small_config();
        let mut chunker = Chunker::new(cfg).unwrap();
        let cuts = chunker.feed(&data);
        let tail = chunker.finalize();

        // Build chunk sizes from cut offsets.
        let mut sizes = Vec::new();
        let mut prev = 0;
        for &cut in &cuts {
            sizes.push(cut - prev);
            prev = cut;
        }
        // The tail (if any) is allowed to be smaller than min.
        // Check non-tail chunks respect [min, max].
        for (i, &size) in sizes.iter().enumerate() {
            assert!(
                size >= cfg.min_chunk,
                "chunk {i} is {size} bytes, below min {}",
                cfg.min_chunk
            );
            assert!(
                size <= cfg.max_chunk,
                "chunk {i} is {size} bytes, above max {}",
                cfg.max_chunk
            );
        }

        // Tail from finalize (last partial chunk) may be < min — that is fine.
        if let Some(t) = tail {
            assert!(t > 0);
            assert!(
                t <= cfg.max_chunk,
                "tail is {t} bytes, above max {}",
                cfg.max_chunk
            );
        }
    }

    #[test]
    fn chunker_small_input_single_chunk() {
        let data = vec![42u8; 32]; // well below min_chunk=64
        let cfg = small_config();
        let mut chunker = Chunker::new(cfg).unwrap();
        let cuts = chunker.feed(&data);
        assert!(
            cuts.is_empty(),
            "no cuts expected for input smaller than min"
        );
        let tail = chunker.finalize();
        assert_eq!(tail, Some(32), "finalize should return remaining 32 bytes");
    }

    #[test]
    fn chunker_empty_input() {
        let mut chunker = Chunker::new(small_config()).unwrap();
        let cuts = chunker.feed(&[]);
        assert!(cuts.is_empty(), "no cuts on empty input");
        assert_eq!(
            chunker.finalize(),
            None,
            "finalize on empty stream should return None"
        );
    }

    #[test]
    fn chunker_forces_cut_at_max() {
        let cfg = small_config();
        // Fill with zeros — constant data is unlikely to trigger a hash boundary,
        // so the only cuts should come from the max_chunk hard limit.
        let data = vec![0u8; cfg.max_chunk * 3];
        let mut chunker = Chunker::new(cfg).unwrap();
        let cuts = chunker.feed(&data);
        assert!(
            !cuts.is_empty(),
            "data larger than max_chunk must produce at least one cut"
        );
        // Every cut must be at most max_chunk bytes from the previous one.
        let mut prev = 0;
        for &cut in &cuts {
            let size = cut - prev;
            assert!(
                size <= cfg.max_chunk,
                "chunk of {size} bytes exceeds max {}",
                cfg.max_chunk
            );
            prev = cut;
        }
    }
}
