/// Generate a 256-entry Gear hash lookup table at compile time using SplitMix64.
const fn generate_gear_table(seed: u64) -> [u64; 256] {
    let mut table = [0u64; 256];
    let mut state = seed;
    let mut i = 0;
    while i < 256 {
        // SplitMix64 step
        state = state.wrapping_add(0x9e3779b97f4a7c15);
        let mut z = state;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d049bb133111eb);
        z = z ^ (z >> 31);
        table[i] = z;
        i += 1;
    }
    table
}

/// Gear hash lookup table: 256 entries generated by SplitMix64 with seed 0.
///
/// Used by the FastCDC content-defined chunking algorithm. Each byte of input
/// is mapped through this table to produce a rolling hash with good statistical
/// properties.
const GEAR_TABLE: [u64; 256] = generate_gear_table(0);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gear_table_is_deterministic() {
        let regenerated = generate_gear_table(0);
        assert_eq!(GEAR_TABLE, regenerated);
    }

    #[test]
    fn gear_table_has_no_obvious_patterns() {
        // No adjacent duplicates
        for i in 1..256 {
            assert_ne!(
                GEAR_TABLE[i - 1],
                GEAR_TABLE[i],
                "adjacent entries {} and {} are duplicates",
                i - 1,
                i
            );
        }
        // No zeros
        for (i, &entry) in GEAR_TABLE.iter().enumerate() {
            assert_ne!(entry, 0, "entry {} is zero", i);
        }
    }

    #[test]
    fn gear_table_first_entry_is_stable() {
        // Pin the first entry to detect seed or algorithm changes.
        assert_eq!(
            GEAR_TABLE[0], 0xe220a8397b1dcdaf,
            "first entry changed — seed or SplitMix64 algorithm was modified"
        );
    }
}
