//! Phase 0h: Candle Validation Loop
//!
//! Verifies that candle produces the same logits as PyTorch for a
//! deterministic tiny model exported to GGUF.
//!
//! Fixtures generated by: python3 -m ct87.generate_validation_fixtures
//! (run from the training/ directory)

use candle_core::quantized::gguf_file;
use candle_core::{Device, Tensor};
use harmony_inference::{HarmonyModel, InferenceCache};
use serde::Deserialize;

#[derive(Deserialize)]
struct ValidationReference {
    input_tokens: Vec<u32>,
    last_logits: Vec<f64>,
}

/// Load the validation GGUF fixture.
fn load_validation_gguf() -> Vec<u8> {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/validation_model.gguf");
    std::fs::read(&path).expect(
        "validation fixture not found; \
         run `python3 -m ct87.generate_validation_fixtures` from training/",
    )
}

/// Load the validation reference JSON fixture.
fn load_validation_reference() -> ValidationReference {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/validation_reference.json");
    let data = std::fs::read_to_string(&path).expect(
        "validation reference not found; \
         run `python3 -m ct87.generate_validation_fixtures` from training/",
    );
    serde_json::from_str(&data).expect("failed to parse validation_reference.json")
}

/// Compute cosine similarity between two f64 slices.
fn cosine_similarity(a: &[f64], b: &[f64]) -> f64 {
    assert_eq!(a.len(), b.len());
    let dot: f64 = a.iter().zip(b.iter()).map(|(x, y)| x * y).sum();
    let norm_a: f64 = a.iter().map(|x| x * x).sum::<f64>().sqrt();
    let norm_b: f64 = b.iter().map(|x| x * x).sum::<f64>().sqrt();
    if norm_a == 0.0 || norm_b == 0.0 {
        return 0.0;
    }
    dot / (norm_a * norm_b)
}

#[test]
fn candle_matches_pytorch_logits() {
    // Load fixtures
    let gguf_data = load_validation_gguf();
    let reference = load_validation_reference();

    // Parse GGUF and load model
    let mut cursor = std::io::Cursor::new(&gguf_data);
    let content =
        gguf_file::Content::read(&mut cursor).expect("failed to parse GGUF");
    let model = HarmonyModel::from_gguf(&content, &mut cursor, &Device::Cpu)
        .expect("failed to load model");

    let config = model.config();
    assert_eq!(
        reference.last_logits.len(),
        config.vocab_size,
        "reference logit count must match vocab_size"
    );

    // Prepare input tensor: [1, seq_len] u32
    let input =
        Tensor::new(reference.input_tokens.as_slice(), &Device::Cpu)
            .expect("failed to create input tensor")
            .reshape((1, reference.input_tokens.len()))
            .expect("failed to reshape input");

    // Forward pass with fresh cache, no engram
    let mut cache = InferenceCache::new(
        config.num_layers,
        config.head_dim,
        config.num_kv_heads,
    );
    let output = model
        .forward(&input, &mut cache, None)
        .expect("forward pass failed");

    // Extract rust logits as f64 for comparison
    let rust_logits_f32: Vec<f32> = output
        .logits
        .flatten_all()
        .expect("flatten failed")
        .to_vec1()
        .expect("to_vec1 failed");
    let rust_logits: Vec<f64> =
        rust_logits_f32.iter().map(|&v| v as f64).collect();

    assert_eq!(
        rust_logits.len(),
        reference.last_logits.len(),
        "logit vector lengths must match"
    );

    // Absolute difference check: max |rust - python| < 1e-5
    let mut max_diff: f64 = 0.0;
    let mut max_diff_idx: usize = 0;
    for (i, (r, p)) in rust_logits
        .iter()
        .zip(reference.last_logits.iter())
        .enumerate()
    {
        let diff = (r - p).abs();
        if diff > max_diff {
            max_diff = diff;
            max_diff_idx = i;
        }
    }

    // Cosine similarity (diagnostic)
    let cos_sim =
        cosine_similarity(&rust_logits, &reference.last_logits);
    println!("Phase 0h validation results:");
    println!(
        "  max absolute diff: {max_diff:.2e} at index {max_diff_idx}"
    );
    println!("  cosine similarity: {cos_sim:.10}");
    println!(
        "  rust logit[{max_diff_idx}]: {:.8}, \
         python logit[{max_diff_idx}]: {:.8}",
        rust_logits[max_diff_idx],
        reference.last_logits[max_diff_idx]
    );

    assert!(
        max_diff < 1e-5,
        "logit mismatch exceeds tolerance: \
         max_diff={max_diff:.2e} at index {max_diff_idx}, \
         rust={:.8}, python={:.8}, \
         cosine_similarity={cos_sim:.10}",
        rust_logits[max_diff_idx],
        reference.last_logits[max_diff_idx],
    );
}
