//! Cross-verification tests against Python Reticulum reference implementation.
//!
//! Test vectors generated by running the Python Reticulum library directly.
//! These verify binary-level compatibility of hashing, destination naming,
//! announce packet parsing, signature verification, and link establishment.

use harmony_crypto::{hash, hkdf};
use harmony_identity::identity::{Identity, PrivateIdentity};
use harmony_reticulum::destination::DestinationName;
use harmony_reticulum::link;
use harmony_reticulum::packet::{Packet, PacketType};
use harmony_reticulum::validate_announce;

// ── Python-generated test vectors ─────────────────────────────────────

/// Identity public key: [32B X25519 pub][32B Ed25519 pub]
const IDENTITY_PUBLIC_KEY: &str =
    "bcd84621fe67b3147a1a30da98f8c6eb58da6f920eedf33114fb6ed5a4dd1545\
     26ed8ace099345ac61ec64e70b69bb3f368d653ccebbfa00ce3d77f5acd0bab7";

/// Identity private key: [32B X25519 secret][32B Ed25519 secret]
const IDENTITY_PRIVATE_KEY: &str =
    "c0e16a6376455dce82e567daa6d37a8a675424e44cd06765364e7cab05837b79\
     81b0d6a6eb0e7c083c8f4d35d43f88d902cde7834d118154e7bdac89dbb82c1c";

/// SHA256(public_key)[:16]
const IDENTITY_HASH: &str = "8e23b5e8904a6bfefbed9275683c2423";

/// SHA256("lxmf.delivery")[:10]
const NAME_HASH_LXMF_DELIVERY: &str = "6ec60bc318e2c0f0d908";

/// SHA256("nomadnetwork.node")[:10]
const NAME_HASH_NOMADNETWORK_NODE: &str = "213e6311bcec54ab4fde";

/// SHA256(name_hash || identity_hash)[:16]
const DESTINATION_HASH: &str = "b87c6512a0dc32fafbba3a9c9fb81b69";

/// Signed data: dest_hash || public_keys || name_hash || random_hash
const SIGNED_DATA: &str =
    "b87c6512a0dc32fafbba3a9c9fb81b69\
     bcd84621fe67b3147a1a30da98f8c6eb58da6f920eedf33114fb6ed5a4dd1545\
     26ed8ace099345ac61ec64e70b69bb3f368d653ccebbfa00ce3d77f5acd0bab7\
     6ec60bc318e2c0f0d908\
     fd1679fab7006553f100";

/// Ed25519 signature of signed_data
const SIGNATURE: &str =
    "ac071a11d3b85c6e47ffab405eef6aeb322b5e2b3ad0d3c817dec5af37c84ace\
     67303a8bc0dab7c73fe5ef9a55b45ac948066f009466c3a7d65d6eeabd05e301";

/// Full announce packet (header + payload)
const FULL_PACKET: &str =
    "0100b87c6512a0dc32fafbba3a9c9fb81b6900\
     bcd84621fe67b3147a1a30da98f8c6eb58da6f920eedf33114fb6ed5a4dd1545\
     26ed8ace099345ac61ec64e70b69bb3f368d653ccebbfa00ce3d77f5acd0bab7\
     6ec60bc318e2c0f0d908\
     fd1679fab7006553f100\
     ac071a11d3b85c6e47ffab405eef6aeb322b5e2b3ad0d3c817dec5af37c84ace\
     67303a8bc0dab7c73fe5ef9a55b45ac948066f009466c3a7d65d6eeabd05e301";

// ── Tests ─────────────────────────────────────────────────────────────

#[test]
fn interop_name_hash_matches_python() {
    let nh = hash::name_hash(b"lxmf.delivery");
    assert_eq!(
        hex::encode(nh),
        NAME_HASH_LXMF_DELIVERY,
        "name_hash('lxmf.delivery') mismatch with Python"
    );

    let nh2 = hash::name_hash(b"nomadnetwork.node");
    assert_eq!(
        hex::encode(nh2),
        NAME_HASH_NOMADNETWORK_NODE,
        "name_hash('nomadnetwork.node') mismatch with Python"
    );
}

#[test]
fn interop_identity_hash_matches_python() {
    let pub_bytes = hex::decode(IDENTITY_PUBLIC_KEY).unwrap();
    let identity = Identity::from_public_bytes(&pub_bytes).unwrap();

    assert_eq!(
        hex::encode(identity.address_hash),
        IDENTITY_HASH,
        "identity address_hash mismatch with Python"
    );
}

#[test]
fn interop_destination_hash_matches_python() {
    let pub_bytes = hex::decode(IDENTITY_PUBLIC_KEY).unwrap();
    let identity = Identity::from_public_bytes(&pub_bytes).unwrap();

    let dest = DestinationName::from_name("lxmf", &["delivery"]).unwrap();
    let dest_hash = dest.destination_hash(&identity.address_hash);

    assert_eq!(
        hex::encode(dest_hash),
        DESTINATION_HASH,
        "destination_hash mismatch with Python"
    );
}

#[test]
fn interop_parse_python_announce_packet() {
    let packet_bytes = hex::decode(FULL_PACKET).unwrap();
    let packet = Packet::from_bytes(&packet_bytes).unwrap();

    // Verify header fields
    assert_eq!(packet.header.flags.packet_type, PacketType::Announce);
    assert!(!packet.header.flags.context_flag); // no ratchet
    assert_eq!(packet.header.hops, 0);
    assert_eq!(hex::encode(packet.header.destination_hash), DESTINATION_HASH);

    // Verify payload size: 64(pubkeys) + 10(name_hash) + 10(random_hash) + 64(sig) = 148
    assert_eq!(packet.data.len(), 148);
}

#[test]
fn interop_validate_python_announce() {
    let packet_bytes = hex::decode(FULL_PACKET).unwrap();
    let packet = Packet::from_bytes(&packet_bytes).unwrap();

    let validated = validate_announce(&packet).unwrap();

    // Identity should match
    assert_eq!(
        hex::encode(validated.identity.address_hash),
        IDENTITY_HASH,
    );

    // Destination hash should match
    assert_eq!(
        hex::encode(validated.destination_hash),
        DESTINATION_HASH,
    );

    // No ratchet, no app_data
    assert!(validated.ratchet.is_none());
    assert!(validated.app_data.is_empty());
}

#[test]
fn interop_signature_matches_python() {
    // Reconstruct the identity from private key bytes
    let prv_bytes = hex::decode(IDENTITY_PRIVATE_KEY).unwrap();
    let private_identity = PrivateIdentity::from_private_bytes(&prv_bytes).unwrap();

    // Build the same signed_data as Python
    let signed_data = hex::decode(SIGNED_DATA).unwrap();

    // Ed25519 is deterministic — same key + same message = same signature
    let signature = private_identity.sign(&signed_data);
    assert_eq!(
        hex::encode(signature),
        SIGNATURE,
        "Ed25519 signature mismatch with Python — indicates key or signed_data divergence"
    );
}

// ── Link establishment interop vectors ───────────────────────────────
//
// Generated by running Python code using the same algorithm as
// Reticulum's Link.py signalling, hashable_part, and HKDF key derivation.

/// Signalling bytes for MTU=500, mode=AES256CBC(1)
const SIGNALLING_MTU500_AES256CBC: &str = "2001f4";

/// Signalling bytes for max MTU (0x1FFFFF), mode=AES256CBC(1)
const SIGNALLING_MAX_MTU_AES256CBC: &str = "3fffff";

/// hashable_part of a link request with known data:
/// flags=0x02 (Single+LinkRequest), dest_hash=b87c65..., context=0x00,
/// ephemeral x25519 pub = 0x00..0x1f, ed25519 pub = 0x20..0x3f, signalling=2001f4
const LINK_HASHABLE_PART: &str =
    "02b87c6512a0dc32fafbba3a9c9fb81b6900\
     000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f\
     202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f\
     2001f4";

/// link_id = SHA256(hashable_part)[:16]
const LINK_ID: &str = "0b9d2ac7c6767a081d7f36e38865f12b";

/// HKDF-SHA256(ikm=0x00..0x1f, salt=link_id, info=[], length=64)
const LINK_DERIVED_KEY: &str =
    "81963961529f000a63383284611c5e6fb967b765694a44567d0d1dcfc8a839a8\
     4cfb871df77108bcae02a7e19433c8f2e76530098ef962ae387d1e98f804a65c";

#[test]
fn interop_signalling_encode_mtu500() {
    // Encode signalling bytes: MTU=500, mode=AES256CBC
    let bytes = link::encode_signalling(500, link::LinkMode::Aes256Cbc);
    assert_eq!(
        hex::encode(bytes),
        SIGNALLING_MTU500_AES256CBC,
        "signalling encode mismatch with Python"
    );
}

#[test]
fn interop_signalling_encode_max_mtu() {
    let bytes = link::encode_signalling(0x1F_FFFF, link::LinkMode::Aes256Cbc);
    assert_eq!(
        hex::encode(bytes),
        SIGNALLING_MAX_MTU_AES256CBC,
        "signalling max MTU encode mismatch with Python"
    );
}

#[test]
fn interop_hashable_part_matches_python() {
    use harmony_reticulum::packet::*;
    use harmony_reticulum::PacketContext;

    let dest_hash = hex::decode(DESTINATION_HASH).unwrap();
    let mut dest_hash_arr = [0u8; 16];
    dest_hash_arr.copy_from_slice(&dest_hash);

    // Build ephemeral keys: x25519 = 0x00..0x1f, ed25519 = 0x20..0x3f
    let mut data = Vec::with_capacity(67);
    data.extend_from_slice(&(0u8..32).collect::<Vec<_>>());
    data.extend_from_slice(&(32u8..64).collect::<Vec<_>>());
    data.extend_from_slice(&hex::decode(SIGNALLING_MTU500_AES256CBC).unwrap());

    let packet = Packet {
        header: PacketHeader {
            flags: PacketFlags {
                ifac: false,
                header_type: HeaderType::Type1,
                context_flag: false,
                propagation: PropagationType::Broadcast,
                destination_type: DestinationType::Single,
                packet_type: PacketType::LinkRequest,
            },
            hops: 0,
            transport_id: None,
            destination_hash: dest_hash_arr,
            context: PacketContext::None,
        },
        data,
    };

    let hp = packet.hashable_part().unwrap();
    assert_eq!(
        hex::encode(&hp),
        LINK_HASHABLE_PART,
        "hashable_part mismatch with Python"
    );
}

#[test]
fn interop_link_id_matches_python() {
    let hashable = hex::decode(LINK_HASHABLE_PART).unwrap();
    let link_id = hash::truncated_hash(&hashable);
    assert_eq!(
        hex::encode(link_id),
        LINK_ID,
        "link_id mismatch with Python"
    );
}

#[test]
fn interop_key_derivation_matches_python() {
    let shared_secret: Vec<u8> = (0u8..32).collect();
    let link_id = hex::decode(LINK_ID).unwrap();

    let derived = hkdf::derive_key_256(&shared_secret, Some(&link_id));
    assert_eq!(
        hex::encode(derived),
        LINK_DERIVED_KEY,
        "HKDF key derivation mismatch with Python"
    );
}
